/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as SitemapStaticDotxmlRouteImport } from './routes/sitemap-static[.]xml'
import { Route as SitemapCountryCodeDotxmlRouteImport } from './routes/sitemap-country-$code[.]xml'
import { Route as SitemapCategorySlugDotxmlRouteImport } from './routes/sitemap-category-$slug[.]xml'
import { Route as PublierRouteImport } from './routes/publier'
import { Route as ProfilRouteImport } from './routes/profil'
import { Route as PlusRouteImport } from './routes/plus'
import { Route as ParametresRouteImport } from './routes/parametres'
import { Route as MonAbonnementRouteImport } from './routes/mon-abonnement'
import { Route as MessagesRouteImport } from './routes/messages'
import { Route as MesStatistiquesRouteImport } from './routes/mes-statistiques'
import { Route as MesAnnoncesRouteImport } from './routes/mes-annonces'
import { Route as KycRouteImport } from './routes/kyc'
import { Route as ExplorerRouteImport } from './routes/explorer'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AbonnementsRouteImport } from './routes/abonnements'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProfilModifierRouteImport } from './routes/profil.modifier'
import { Route as PaiementSuccesRouteImport } from './routes/paiement.succes'
import { Route as BoutiqueOwnerIdRouteImport } from './routes/boutique.$ownerId'
import { Route as BoostIdRouteImport } from './routes/boost.$id'
import { Route as AnnoncesIdRouteImport } from './routes/annonces.$id'
import { Route as ApiPublicPaydunyaIpnRouteImport } from './routes/api/public/paydunya-ipn'
import { Route as AnnoncesIdEditRouteImport } from './routes/annonces.$id.edit'
import { Route as ApiPublicHooksPushBoostNudgeRouteImport } from './routes/api/public/hooks/push-boost-nudge'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapStaticDotxmlRoute = SitemapStaticDotxmlRouteImport.update({
  id: '/sitemap-static.xml',
  path: '/sitemap-static.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapCountryCodeDotxmlRoute =
  SitemapCountryCodeDotxmlRouteImport.update({
    id: '/sitemap-country-$code.xml',
    path: '/sitemap-country-$code.xml',
    getParentRoute: () => rootRouteImport,
  } as any)
const SitemapCategorySlugDotxmlRoute =
  SitemapCategorySlugDotxmlRouteImport.update({
    id: '/sitemap-category-$slug.xml',
    path: '/sitemap-category-$slug.xml',
    getParentRoute: () => rootRouteImport,
  } as any)
const PublierRoute = PublierRouteImport.update({
  id: '/publier',
  path: '/publier',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfilRoute = ProfilRouteImport.update({
  id: '/profil',
  path: '/profil',
  getParentRoute: () => rootRouteImport,
} as any)
const PlusRoute = PlusRouteImport.update({
  id: '/plus',
  path: '/plus',
  getParentRoute: () => rootRouteImport,
} as any)
const ParametresRoute = ParametresRouteImport.update({
  id: '/parametres',
  path: '/parametres',
  getParentRoute: () => rootRouteImport,
} as any)
const MonAbonnementRoute = MonAbonnementRouteImport.update({
  id: '/mon-abonnement',
  path: '/mon-abonnement',
  getParentRoute: () => rootRouteImport,
} as any)
const MessagesRoute = MessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => rootRouteImport,
} as any)
const MesStatistiquesRoute = MesStatistiquesRouteImport.update({
  id: '/mes-statistiques',
  path: '/mes-statistiques',
  getParentRoute: () => rootRouteImport,
} as any)
const MesAnnoncesRoute = MesAnnoncesRouteImport.update({
  id: '/mes-annonces',
  path: '/mes-annonces',
  getParentRoute: () => rootRouteImport,
} as any)
const KycRoute = KycRouteImport.update({
  id: '/kyc',
  path: '/kyc',
  getParentRoute: () => rootRouteImport,
} as any)
const ExplorerRoute = ExplorerRouteImport.update({
  id: '/explorer',
  path: '/explorer',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AbonnementsRoute = AbonnementsRouteImport.update({
  id: '/abonnements',
  path: '/abonnements',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfilModifierRoute = ProfilModifierRouteImport.update({
  id: '/modifier',
  path: '/modifier',
  getParentRoute: () => ProfilRoute,
} as any)
const PaiementSuccesRoute = PaiementSuccesRouteImport.update({
  id: '/paiement/succes',
  path: '/paiement/succes',
  getParentRoute: () => rootRouteImport,
} as any)
const BoutiqueOwnerIdRoute = BoutiqueOwnerIdRouteImport.update({
  id: '/boutique/$ownerId',
  path: '/boutique/$ownerId',
  getParentRoute: () => rootRouteImport,
} as any)
const BoostIdRoute = BoostIdRouteImport.update({
  id: '/boost/$id',
  path: '/boost/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AnnoncesIdRoute = AnnoncesIdRouteImport.update({
  id: '/annonces/$id',
  path: '/annonces/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicPaydunyaIpnRoute = ApiPublicPaydunyaIpnRouteImport.update({
  id: '/api/public/paydunya-ipn',
  path: '/api/public/paydunya-ipn',
  getParentRoute: () => rootRouteImport,
} as any)
const AnnoncesIdEditRoute = AnnoncesIdEditRouteImport.update({
  id: '/edit',
  path: '/edit',
  getParentRoute: () => AnnoncesIdRoute,
} as any)
const ApiPublicHooksPushBoostNudgeRoute =
  ApiPublicHooksPushBoostNudgeRouteImport.update({
    id: '/api/public/hooks/push-boost-nudge',
    path: '/api/public/hooks/push-boost-nudge',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/abonnements': typeof AbonnementsRoute
  '/auth': typeof AuthRoute
  '/explorer': typeof ExplorerRoute
  '/kyc': typeof KycRoute
  '/mes-annonces': typeof MesAnnoncesRoute
  '/mes-statistiques': typeof MesStatistiquesRoute
  '/messages': typeof MessagesRoute
  '/mon-abonnement': typeof MonAbonnementRoute
  '/parametres': typeof ParametresRoute
  '/plus': typeof PlusRoute
  '/profil': typeof ProfilRouteWithChildren
  '/publier': typeof PublierRoute
  '/sitemap-category-$slug.xml': typeof SitemapCategorySlugDotxmlRoute
  '/sitemap-country-$code.xml': typeof SitemapCountryCodeDotxmlRoute
  '/sitemap-static.xml': typeof SitemapStaticDotxmlRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/annonces/$id': typeof AnnoncesIdRouteWithChildren
  '/boost/$id': typeof BoostIdRoute
  '/boutique/$ownerId': typeof BoutiqueOwnerIdRoute
  '/paiement/succes': typeof PaiementSuccesRoute
  '/profil/modifier': typeof ProfilModifierRoute
  '/annonces/$id/edit': typeof AnnoncesIdEditRoute
  '/api/public/paydunya-ipn': typeof ApiPublicPaydunyaIpnRoute
  '/api/public/hooks/push-boost-nudge': typeof ApiPublicHooksPushBoostNudgeRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/abonnements': typeof AbonnementsRoute
  '/auth': typeof AuthRoute
  '/explorer': typeof ExplorerRoute
  '/kyc': typeof KycRoute
  '/mes-annonces': typeof MesAnnoncesRoute
  '/mes-statistiques': typeof MesStatistiquesRoute
  '/messages': typeof MessagesRoute
  '/mon-abonnement': typeof MonAbonnementRoute
  '/parametres': typeof ParametresRoute
  '/plus': typeof PlusRoute
  '/profil': typeof ProfilRouteWithChildren
  '/publier': typeof PublierRoute
  '/sitemap-category-$slug.xml': typeof SitemapCategorySlugDotxmlRoute
  '/sitemap-country-$code.xml': typeof SitemapCountryCodeDotxmlRoute
  '/sitemap-static.xml': typeof SitemapStaticDotxmlRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/annonces/$id': typeof AnnoncesIdRouteWithChildren
  '/boost/$id': typeof BoostIdRoute
  '/boutique/$ownerId': typeof BoutiqueOwnerIdRoute
  '/paiement/succes': typeof PaiementSuccesRoute
  '/profil/modifier': typeof ProfilModifierRoute
  '/annonces/$id/edit': typeof AnnoncesIdEditRoute
  '/api/public/paydunya-ipn': typeof ApiPublicPaydunyaIpnRoute
  '/api/public/hooks/push-boost-nudge': typeof ApiPublicHooksPushBoostNudgeRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/abonnements': typeof AbonnementsRoute
  '/auth': typeof AuthRoute
  '/explorer': typeof ExplorerRoute
  '/kyc': typeof KycRoute
  '/mes-annonces': typeof MesAnnoncesRoute
  '/mes-statistiques': typeof MesStatistiquesRoute
  '/messages': typeof MessagesRoute
  '/mon-abonnement': typeof MonAbonnementRoute
  '/parametres': typeof ParametresRoute
  '/plus': typeof PlusRoute
  '/profil': typeof ProfilRouteWithChildren
  '/publier': typeof PublierRoute
  '/sitemap-category-$slug.xml': typeof SitemapCategorySlugDotxmlRoute
  '/sitemap-country-$code.xml': typeof SitemapCountryCodeDotxmlRoute
  '/sitemap-static.xml': typeof SitemapStaticDotxmlRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/annonces/$id': typeof AnnoncesIdRouteWithChildren
  '/boost/$id': typeof BoostIdRoute
  '/boutique/$ownerId': typeof BoutiqueOwnerIdRoute
  '/paiement/succes': typeof PaiementSuccesRoute
  '/profil/modifier': typeof ProfilModifierRoute
  '/annonces/$id/edit': typeof AnnoncesIdEditRoute
  '/api/public/paydunya-ipn': typeof ApiPublicPaydunyaIpnRoute
  '/api/public/hooks/push-boost-nudge': typeof ApiPublicHooksPushBoostNudgeRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/abonnements'
    | '/auth'
    | '/explorer'
    | '/kyc'
    | '/mes-annonces'
    | '/mes-statistiques'
    | '/messages'
    | '/mon-abonnement'
    | '/parametres'
    | '/plus'
    | '/profil'
    | '/publier'
    | '/sitemap-category-$slug.xml'
    | '/sitemap-country-$code.xml'
    | '/sitemap-static.xml'
    | '/sitemap.xml'
    | '/annonces/$id'
    | '/boost/$id'
    | '/boutique/$ownerId'
    | '/paiement/succes'
    | '/profil/modifier'
    | '/annonces/$id/edit'
    | '/api/public/paydunya-ipn'
    | '/api/public/hooks/push-boost-nudge'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/abonnements'
    | '/auth'
    | '/explorer'
    | '/kyc'
    | '/mes-annonces'
    | '/mes-statistiques'
    | '/messages'
    | '/mon-abonnement'
    | '/parametres'
    | '/plus'
    | '/profil'
    | '/publier'
    | '/sitemap-category-$slug.xml'
    | '/sitemap-country-$code.xml'
    | '/sitemap-static.xml'
    | '/sitemap.xml'
    | '/annonces/$id'
    | '/boost/$id'
    | '/boutique/$ownerId'
    | '/paiement/succes'
    | '/profil/modifier'
    | '/annonces/$id/edit'
    | '/api/public/paydunya-ipn'
    | '/api/public/hooks/push-boost-nudge'
  id:
    | '__root__'
    | '/'
    | '/abonnements'
    | '/auth'
    | '/explorer'
    | '/kyc'
    | '/mes-annonces'
    | '/mes-statistiques'
    | '/messages'
    | '/mon-abonnement'
    | '/parametres'
    | '/plus'
    | '/profil'
    | '/publier'
    | '/sitemap-category-$slug.xml'
    | '/sitemap-country-$code.xml'
    | '/sitemap-static.xml'
    | '/sitemap.xml'
    | '/annonces/$id'
    | '/boost/$id'
    | '/boutique/$ownerId'
    | '/paiement/succes'
    | '/profil/modifier'
    | '/annonces/$id/edit'
    | '/api/public/paydunya-ipn'
    | '/api/public/hooks/push-boost-nudge'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AbonnementsRoute: typeof AbonnementsRoute
  AuthRoute: typeof AuthRoute
  ExplorerRoute: typeof ExplorerRoute
  KycRoute: typeof KycRoute
  MesAnnoncesRoute: typeof MesAnnoncesRoute
  MesStatistiquesRoute: typeof MesStatistiquesRoute
  MessagesRoute: typeof MessagesRoute
  MonAbonnementRoute: typeof MonAbonnementRoute
  ParametresRoute: typeof ParametresRoute
  PlusRoute: typeof PlusRoute
  ProfilRoute: typeof ProfilRouteWithChildren
  PublierRoute: typeof PublierRoute
  SitemapCategorySlugDotxmlRoute: typeof SitemapCategorySlugDotxmlRoute
  SitemapCountryCodeDotxmlRoute: typeof SitemapCountryCodeDotxmlRoute
  SitemapStaticDotxmlRoute: typeof SitemapStaticDotxmlRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  AnnoncesIdRoute: typeof AnnoncesIdRouteWithChildren
  BoostIdRoute: typeof BoostIdRoute
  BoutiqueOwnerIdRoute: typeof BoutiqueOwnerIdRoute
  PaiementSuccesRoute: typeof PaiementSuccesRoute
  ApiPublicPaydunyaIpnRoute: typeof ApiPublicPaydunyaIpnRoute
  ApiPublicHooksPushBoostNudgeRoute: typeof ApiPublicHooksPushBoostNudgeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap-static.xml': {
      id: '/sitemap-static.xml'
      path: '/sitemap-static.xml'
      fullPath: '/sitemap-static.xml'
      preLoaderRoute: typeof SitemapStaticDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap-country-$code.xml': {
      id: '/sitemap-country-$code.xml'
      path: '/sitemap-country-$code.xml'
      fullPath: '/sitemap-country-$code.xml'
      preLoaderRoute: typeof SitemapCountryCodeDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap-category-$slug.xml': {
      id: '/sitemap-category-$slug.xml'
      path: '/sitemap-category-$slug.xml'
      fullPath: '/sitemap-category-$slug.xml'
      preLoaderRoute: typeof SitemapCategorySlugDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/publier': {
      id: '/publier'
      path: '/publier'
      fullPath: '/publier'
      preLoaderRoute: typeof PublierRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profil': {
      id: '/profil'
      path: '/profil'
      fullPath: '/profil'
      preLoaderRoute: typeof ProfilRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/plus': {
      id: '/plus'
      path: '/plus'
      fullPath: '/plus'
      preLoaderRoute: typeof PlusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/parametres': {
      id: '/parametres'
      path: '/parametres'
      fullPath: '/parametres'
      preLoaderRoute: typeof ParametresRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mon-abonnement': {
      id: '/mon-abonnement'
      path: '/mon-abonnement'
      fullPath: '/mon-abonnement'
      preLoaderRoute: typeof MonAbonnementRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/messages': {
      id: '/messages'
      path: '/messages'
      fullPath: '/messages'
      preLoaderRoute: typeof MessagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mes-statistiques': {
      id: '/mes-statistiques'
      path: '/mes-statistiques'
      fullPath: '/mes-statistiques'
      preLoaderRoute: typeof MesStatistiquesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mes-annonces': {
      id: '/mes-annonces'
      path: '/mes-annonces'
      fullPath: '/mes-annonces'
      preLoaderRoute: typeof MesAnnoncesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kyc': {
      id: '/kyc'
      path: '/kyc'
      fullPath: '/kyc'
      preLoaderRoute: typeof KycRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/explorer': {
      id: '/explorer'
      path: '/explorer'
      fullPath: '/explorer'
      preLoaderRoute: typeof ExplorerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/abonnements': {
      id: '/abonnements'
      path: '/abonnements'
      fullPath: '/abonnements'
      preLoaderRoute: typeof AbonnementsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profil/modifier': {
      id: '/profil/modifier'
      path: '/modifier'
      fullPath: '/profil/modifier'
      preLoaderRoute: typeof ProfilModifierRouteImport
      parentRoute: typeof ProfilRoute
    }
    '/paiement/succes': {
      id: '/paiement/succes'
      path: '/paiement/succes'
      fullPath: '/paiement/succes'
      preLoaderRoute: typeof PaiementSuccesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/boutique/$ownerId': {
      id: '/boutique/$ownerId'
      path: '/boutique/$ownerId'
      fullPath: '/boutique/$ownerId'
      preLoaderRoute: typeof BoutiqueOwnerIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/boost/$id': {
      id: '/boost/$id'
      path: '/boost/$id'
      fullPath: '/boost/$id'
      preLoaderRoute: typeof BoostIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/annonces/$id': {
      id: '/annonces/$id'
      path: '/annonces/$id'
      fullPath: '/annonces/$id'
      preLoaderRoute: typeof AnnoncesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/paydunya-ipn': {
      id: '/api/public/paydunya-ipn'
      path: '/api/public/paydunya-ipn'
      fullPath: '/api/public/paydunya-ipn'
      preLoaderRoute: typeof ApiPublicPaydunyaIpnRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/annonces/$id/edit': {
      id: '/annonces/$id/edit'
      path: '/edit'
      fullPath: '/annonces/$id/edit'
      preLoaderRoute: typeof AnnoncesIdEditRouteImport
      parentRoute: typeof AnnoncesIdRoute
    }
    '/api/public/hooks/push-boost-nudge': {
      id: '/api/public/hooks/push-boost-nudge'
      path: '/api/public/hooks/push-boost-nudge'
      fullPath: '/api/public/hooks/push-boost-nudge'
      preLoaderRoute: typeof ApiPublicHooksPushBoostNudgeRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface ProfilRouteChildren {
  ProfilModifierRoute: typeof ProfilModifierRoute
}

const ProfilRouteChildren: ProfilRouteChildren = {
  ProfilModifierRoute: ProfilModifierRoute,
}

const ProfilRouteWithChildren =
  ProfilRoute._addFileChildren(ProfilRouteChildren)

interface AnnoncesIdRouteChildren {
  AnnoncesIdEditRoute: typeof AnnoncesIdEditRoute
}

const AnnoncesIdRouteChildren: AnnoncesIdRouteChildren = {
  AnnoncesIdEditRoute: AnnoncesIdEditRoute,
}

const AnnoncesIdRouteWithChildren = AnnoncesIdRoute._addFileChildren(
  AnnoncesIdRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AbonnementsRoute: AbonnementsRoute,
  AuthRoute: AuthRoute,
  ExplorerRoute: ExplorerRoute,
  KycRoute: KycRoute,
  MesAnnoncesRoute: MesAnnoncesRoute,
  MesStatistiquesRoute: MesStatistiquesRoute,
  MessagesRoute: MessagesRoute,
  MonAbonnementRoute: MonAbonnementRoute,
  ParametresRoute: ParametresRoute,
  PlusRoute: PlusRoute,
  ProfilRoute: ProfilRouteWithChildren,
  PublierRoute: PublierRoute,
  SitemapCategorySlugDotxmlRoute: SitemapCategorySlugDotxmlRoute,
  SitemapCountryCodeDotxmlRoute: SitemapCountryCodeDotxmlRoute,
  SitemapStaticDotxmlRoute: SitemapStaticDotxmlRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  AnnoncesIdRoute: AnnoncesIdRouteWithChildren,
  BoostIdRoute: BoostIdRoute,
  BoutiqueOwnerIdRoute: BoutiqueOwnerIdRoute,
  PaiementSuccesRoute: PaiementSuccesRoute,
  ApiPublicPaydunyaIpnRoute: ApiPublicPaydunyaIpnRoute,
  ApiPublicHooksPushBoostNudgeRoute: ApiPublicHooksPushBoostNudgeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
