/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PublierRouteImport } from './routes/publier'
import { Route as ProfilRouteImport } from './routes/profil'
import { Route as ParametresRouteImport } from './routes/parametres'
import { Route as MonAbonnementRouteImport } from './routes/mon-abonnement'
import { Route as MessagesRouteImport } from './routes/messages'
import { Route as MesStatistiquesRouteImport } from './routes/mes-statistiques'
import { Route as MesAnnoncesRouteImport } from './routes/mes-annonces'
import { Route as ExplorerRouteImport } from './routes/explorer'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AbonnementsRouteImport } from './routes/abonnements'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PaiementSuccesRouteImport } from './routes/paiement.succes'
import { Route as BoostIdRouteImport } from './routes/boost.$id'
import { Route as AnnoncesIdRouteImport } from './routes/annonces.$id'
import { Route as ApiPublicPaydunyaIpnRouteImport } from './routes/api/public/paydunya-ipn'
import { Route as AnnoncesIdEditRouteImport } from './routes/annonces.$id.edit'

const PublierRoute = PublierRouteImport.update({
  id: '/publier',
  path: '/publier',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfilRoute = ProfilRouteImport.update({
  id: '/profil',
  path: '/profil',
  getParentRoute: () => rootRouteImport,
} as any)
const ParametresRoute = ParametresRouteImport.update({
  id: '/parametres',
  path: '/parametres',
  getParentRoute: () => rootRouteImport,
} as any)
const MonAbonnementRoute = MonAbonnementRouteImport.update({
  id: '/mon-abonnement',
  path: '/mon-abonnement',
  getParentRoute: () => rootRouteImport,
} as any)
const MessagesRoute = MessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => rootRouteImport,
} as any)
const MesStatistiquesRoute = MesStatistiquesRouteImport.update({
  id: '/mes-statistiques',
  path: '/mes-statistiques',
  getParentRoute: () => rootRouteImport,
} as any)
const MesAnnoncesRoute = MesAnnoncesRouteImport.update({
  id: '/mes-annonces',
  path: '/mes-annonces',
  getParentRoute: () => rootRouteImport,
} as any)
const ExplorerRoute = ExplorerRouteImport.update({
  id: '/explorer',
  path: '/explorer',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AbonnementsRoute = AbonnementsRouteImport.update({
  id: '/abonnements',
  path: '/abonnements',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PaiementSuccesRoute = PaiementSuccesRouteImport.update({
  id: '/paiement/succes',
  path: '/paiement/succes',
  getParentRoute: () => rootRouteImport,
} as any)
const BoostIdRoute = BoostIdRouteImport.update({
  id: '/boost/$id',
  path: '/boost/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AnnoncesIdRoute = AnnoncesIdRouteImport.update({
  id: '/annonces/$id',
  path: '/annonces/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicPaydunyaIpnRoute = ApiPublicPaydunyaIpnRouteImport.update({
  id: '/api/public/paydunya-ipn',
  path: '/api/public/paydunya-ipn',
  getParentRoute: () => rootRouteImport,
} as any)
const AnnoncesIdEditRoute = AnnoncesIdEditRouteImport.update({
  id: '/edit',
  path: '/edit',
  getParentRoute: () => AnnoncesIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/abonnements': typeof AbonnementsRoute
  '/auth': typeof AuthRoute
  '/explorer': typeof ExplorerRoute
  '/mes-annonces': typeof MesAnnoncesRoute
  '/mes-statistiques': typeof MesStatistiquesRoute
  '/messages': typeof MessagesRoute
  '/mon-abonnement': typeof MonAbonnementRoute
  '/parametres': typeof ParametresRoute
  '/profil': typeof ProfilRoute
  '/publier': typeof PublierRoute
  '/annonces/$id': typeof AnnoncesIdRouteWithChildren
  '/boost/$id': typeof BoostIdRoute
  '/paiement/succes': typeof PaiementSuccesRoute
  '/annonces/$id/edit': typeof AnnoncesIdEditRoute
  '/api/public/paydunya-ipn': typeof ApiPublicPaydunyaIpnRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/abonnements': typeof AbonnementsRoute
  '/auth': typeof AuthRoute
  '/explorer': typeof ExplorerRoute
  '/mes-annonces': typeof MesAnnoncesRoute
  '/mes-statistiques': typeof MesStatistiquesRoute
  '/messages': typeof MessagesRoute
  '/mon-abonnement': typeof MonAbonnementRoute
  '/parametres': typeof ParametresRoute
  '/profil': typeof ProfilRoute
  '/publier': typeof PublierRoute
  '/annonces/$id': typeof AnnoncesIdRouteWithChildren
  '/boost/$id': typeof BoostIdRoute
  '/paiement/succes': typeof PaiementSuccesRoute
  '/annonces/$id/edit': typeof AnnoncesIdEditRoute
  '/api/public/paydunya-ipn': typeof ApiPublicPaydunyaIpnRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/abonnements': typeof AbonnementsRoute
  '/auth': typeof AuthRoute
  '/explorer': typeof ExplorerRoute
  '/mes-annonces': typeof MesAnnoncesRoute
  '/mes-statistiques': typeof MesStatistiquesRoute
  '/messages': typeof MessagesRoute
  '/mon-abonnement': typeof MonAbonnementRoute
  '/parametres': typeof ParametresRoute
  '/profil': typeof ProfilRoute
  '/publier': typeof PublierRoute
  '/annonces/$id': typeof AnnoncesIdRouteWithChildren
  '/boost/$id': typeof BoostIdRoute
  '/paiement/succes': typeof PaiementSuccesRoute
  '/annonces/$id/edit': typeof AnnoncesIdEditRoute
  '/api/public/paydunya-ipn': typeof ApiPublicPaydunyaIpnRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/abonnements'
    | '/auth'
    | '/explorer'
    | '/mes-annonces'
    | '/mes-statistiques'
    | '/messages'
    | '/mon-abonnement'
    | '/parametres'
    | '/profil'
    | '/publier'
    | '/annonces/$id'
    | '/boost/$id'
    | '/paiement/succes'
    | '/annonces/$id/edit'
    | '/api/public/paydunya-ipn'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/abonnements'
    | '/auth'
    | '/explorer'
    | '/mes-annonces'
    | '/mes-statistiques'
    | '/messages'
    | '/mon-abonnement'
    | '/parametres'
    | '/profil'
    | '/publier'
    | '/annonces/$id'
    | '/boost/$id'
    | '/paiement/succes'
    | '/annonces/$id/edit'
    | '/api/public/paydunya-ipn'
  id:
    | '__root__'
    | '/'
    | '/abonnements'
    | '/auth'
    | '/explorer'
    | '/mes-annonces'
    | '/mes-statistiques'
    | '/messages'
    | '/mon-abonnement'
    | '/parametres'
    | '/profil'
    | '/publier'
    | '/annonces/$id'
    | '/boost/$id'
    | '/paiement/succes'
    | '/annonces/$id/edit'
    | '/api/public/paydunya-ipn'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AbonnementsRoute: typeof AbonnementsRoute
  AuthRoute: typeof AuthRoute
  ExplorerRoute: typeof ExplorerRoute
  MesAnnoncesRoute: typeof MesAnnoncesRoute
  MesStatistiquesRoute: typeof MesStatistiquesRoute
  MessagesRoute: typeof MessagesRoute
  MonAbonnementRoute: typeof MonAbonnementRoute
  ParametresRoute: typeof ParametresRoute
  ProfilRoute: typeof ProfilRoute
  PublierRoute: typeof PublierRoute
  AnnoncesIdRoute: typeof AnnoncesIdRouteWithChildren
  BoostIdRoute: typeof BoostIdRoute
  PaiementSuccesRoute: typeof PaiementSuccesRoute
  ApiPublicPaydunyaIpnRoute: typeof ApiPublicPaydunyaIpnRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/publier': {
      id: '/publier'
      path: '/publier'
      fullPath: '/publier'
      preLoaderRoute: typeof PublierRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profil': {
      id: '/profil'
      path: '/profil'
      fullPath: '/profil'
      preLoaderRoute: typeof ProfilRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/parametres': {
      id: '/parametres'
      path: '/parametres'
      fullPath: '/parametres'
      preLoaderRoute: typeof ParametresRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mon-abonnement': {
      id: '/mon-abonnement'
      path: '/mon-abonnement'
      fullPath: '/mon-abonnement'
      preLoaderRoute: typeof MonAbonnementRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/messages': {
      id: '/messages'
      path: '/messages'
      fullPath: '/messages'
      preLoaderRoute: typeof MessagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mes-statistiques': {
      id: '/mes-statistiques'
      path: '/mes-statistiques'
      fullPath: '/mes-statistiques'
      preLoaderRoute: typeof MesStatistiquesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mes-annonces': {
      id: '/mes-annonces'
      path: '/mes-annonces'
      fullPath: '/mes-annonces'
      preLoaderRoute: typeof MesAnnoncesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/explorer': {
      id: '/explorer'
      path: '/explorer'
      fullPath: '/explorer'
      preLoaderRoute: typeof ExplorerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/abonnements': {
      id: '/abonnements'
      path: '/abonnements'
      fullPath: '/abonnements'
      preLoaderRoute: typeof AbonnementsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/paiement/succes': {
      id: '/paiement/succes'
      path: '/paiement/succes'
      fullPath: '/paiement/succes'
      preLoaderRoute: typeof PaiementSuccesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/boost/$id': {
      id: '/boost/$id'
      path: '/boost/$id'
      fullPath: '/boost/$id'
      preLoaderRoute: typeof BoostIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/annonces/$id': {
      id: '/annonces/$id'
      path: '/annonces/$id'
      fullPath: '/annonces/$id'
      preLoaderRoute: typeof AnnoncesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/paydunya-ipn': {
      id: '/api/public/paydunya-ipn'
      path: '/api/public/paydunya-ipn'
      fullPath: '/api/public/paydunya-ipn'
      preLoaderRoute: typeof ApiPublicPaydunyaIpnRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/annonces/$id/edit': {
      id: '/annonces/$id/edit'
      path: '/edit'
      fullPath: '/annonces/$id/edit'
      preLoaderRoute: typeof AnnoncesIdEditRouteImport
      parentRoute: typeof AnnoncesIdRoute
    }
  }
}

interface AnnoncesIdRouteChildren {
  AnnoncesIdEditRoute: typeof AnnoncesIdEditRoute
}

const AnnoncesIdRouteChildren: AnnoncesIdRouteChildren = {
  AnnoncesIdEditRoute: AnnoncesIdEditRoute,
}

const AnnoncesIdRouteWithChildren = AnnoncesIdRoute._addFileChildren(
  AnnoncesIdRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AbonnementsRoute: AbonnementsRoute,
  AuthRoute: AuthRoute,
  ExplorerRoute: ExplorerRoute,
  MesAnnoncesRoute: MesAnnoncesRoute,
  MesStatistiquesRoute: MesStatistiquesRoute,
  MessagesRoute: MessagesRoute,
  MonAbonnementRoute: MonAbonnementRoute,
  ParametresRoute: ParametresRoute,
  ProfilRoute: ProfilRoute,
  PublierRoute: PublierRoute,
  AnnoncesIdRoute: AnnoncesIdRouteWithChildren,
  BoostIdRoute: BoostIdRoute,
  PaiementSuccesRoute: PaiementSuccesRoute,
  ApiPublicPaydunyaIpnRoute: ApiPublicPaydunyaIpnRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
